project_id = "mbddyejgznxdlabnlght"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[functions.search-disaster-resources]
verify_jwt = false

[functions.get-weather-data]
verify_jwt = false

[functions.get-fire-data]
verify_jwt = false

[functions.get-maps-api-key]
verify_jwt = false

[functions.search-openai-resources]
verify_jwt = false

[functions.search-perplexity-resources]
verify_jwt = false

[functions.search-recovery-resources]
verify_jwt = false